### PR TITLE
Merge upstream main

### PR DESCRIPTION
**Pull request by mxgrey**
In #11 I had merged the upstream `main` branch into the PR, but possibly due to a squash commit the git history did not recognize that these commits were accounted for after the squash happened.

This PR doesn't change any lines of code but will allow git to recognize that these commits are accounted for, allowing for a nicer diff.

Please do a regular merge commit (not a squash commit) on this or else it won't have the desired effect.

### CODE REVIEW

**Comment by mxgrey** [comment]
@geoff-imdex 

After #13 was merged, we only see one commit [622e887](https://github.com/ros2-rust/ros2_rust/pull/422/commits/622e887c7112463c68aef05d12c3b08be68c42ef) show up in the upstream PR, which suggests that was a squash-merge instead of a merge-commit.

Are you certain that you did a merge-commit of #13 or did you possibly do a squash commit? If that was a squash commit then you'll need to reopen this PR and do a merge-commit of it, otherwise the PR in ros2-rust will be very difficult for them to review since it will contain a lot of extraneous diffs from previous PRs.

**Comment by mxgrey** [comment]
Just to be clear, this PR has a diff of zero lines, but that's on purpose. The important thing is we need your main branch to recognize the individual commits that already exist on the upstream ros2-rust main branch, otherwise GitHub will not be able to produce an accurate code diff for reviewers.

In order to have the individual commits on your main branch, this PR **cannot** be merged with the squash option, it needs to be merged as a regular merge-commit.

**Comment by mxgrey** [comment]
In case it helps to clarify: When you see the option to squash merge the PR, click the arrow button next to it and select `Create a merge commit`, as highlighted here:

merge-commit

**Comment by geoff-imdex** [comment]
Would it be better if sync'd my master "fork" with the upstream branch - this should allow git to determine that the changes are the same (and hopefully not create a load of conflicts) and reduce the set of changes to the pertinent ones?
If needs be I can do as you suggest and create a merge-commit.
And apologies for the broken process - I've blindly followed a process I've been using for years without really thinking how the upstream commits were being brought in to my PR and the effect that would have.

**Comment by mxgrey** [comment]
> Would it be better if sync'd my master "fork" with the upstream branch

If you mean doing something like `$ git merge upstream/main` into your fork's main branch, then that will have the exact same effect as doing a merge-commit of this PR, so that would be fine. If you're talking about doing something else, I would advise against it.

>  this should allow git to determine that the changes are the same (and hopefully not create a load of conflicts) and reduce the set of changes to the pertinent ones?

I don't think there's any way to get around GitHub having the wrong diff without the commits from main being present on your branch. There aren't merge conflicts currently and there still won't be merge conflicts if you just do a commit-merge of this PR.

> And apologies for the broken process

Git is very confusing tool and even my own mastery of it is limited, so no worries. I'm just trying to make sure that it's easy as possible for the maintainers to review the PR, and until we get these specific commits merged in properly, the maintainers will have thousands of extraneous lines in the diff which are actually coming from other PRs that were already approved and merged.

**Comment by geoff-imdex** [comment]
I was referring to this GitHub feature 
image, which no doubt does the git merge behind the scenes.  In retrospect, I should have done this first before applying your commits as this would have tidied things up.
Given where things are at, I'll follow your suggested process - and I've just realised you added a helpful comment at the top of this and PR13 - or at least it would have been helpful if I'd read them (face meet palm :))

**Pull request merged**
